### ISSUE TITLE
Tests failing with arango 3.3.2

### ISSUE THREAD

**Issue by pablobcb** [beno/xarango#13]
9) test execute transaction (TransactionTest)
     test/transaction_test.exs:18
     ** (Xarango.Error) unknown path '/_api/transaction/'
     code: result = %Transaction{ collections: %{}, action: "function(){return \"Hello\"}" } |> Transaction.execute
     stacktrace:
       (xarango) lib/xarango/util.ex:80: Xarango.Util.do_error/1
       (xarango) lib/xarango/transaction.ex:28: Xarango.Transaction.execute/2
       test/transaction_test.exs:19: (test)

**Comment by beno** [comment]
Thank you, I will look into it.

**Comment by jnylen** [comment]
@beno,
Did you have time to look into it yet?

**Comment by liketemple** [comment]
meet same issue

**Comment by chintan-mishra** [comment]
Elixir 1.7 has deprecated some functions which need to be changed.

**Comment by chintan-mishra** [comment]
@pablobcb  @jnylen  @liketemple 

~~We have forked the project and are supporting it on best efforts basis. Being a 2 members developer team we cannot devote the required time to build all the features. However, some mission-critical features have been corrected.~~

~~*Can you please contribute in the project referenced below and help it grow?* **Thus, allowing you to get involved with the Elixir community.**~~

~~By Mar 2019, we hope to have all the necessary features available and documented.~~
The project is still available but archived. It works well with ArangoDB 3.3.x but with limited support for 3.2.x and lower. We have done some work to get you started with developing for 3.4.x
https://gitlab.com/Rebhu_Computing/open-source/xarango

~~You can help by doing the following:~~
~~0: Implement missing/incomplete features~~
~~1: Code review~~
~~2: Write docs~~
~~3: Identifying bugs~~
~~4: Miscellaneous tasks~~

**Comment by jnylen** [comment]
Hi again @chintan-mishra,
I'm moving over most projects to Durango instead, we should really combine these two projects only parts missing are the graph and transaction parts which shouldn't be that hard.

**Comment by chintan-mishra** [comment]
@jnylen 
We are using Xarango in prod. It'd be hard to switch to Durango while it is still nascent.

We should figure out the details in Durango's issues.

**Comment by chintan-mishra** [comment]
[At 8hoot](https://8hoot.com), we have migrated to CouchDB due to certain issues with ArangoDB while just starting to scale up. So, I won't be able to work on this anymore. Hope you don't mind.

**Comment by SuperFluffy** [comment]
@chintan-mishra Could you make a little write up on what issues you faced when working with ArangoDB? I am considering ArangoDB for one of my projects because its many features sound tempting, but there aren't very many users out there (and hence few articles where people share their experience).

**Comment by chintan-mishra** [comment]
@SuperFluffy I was occupied in some work for past few days so I could not reply sooner. I have been asked this by a few people. Here is a small article that tells what led us to our decision.

https://medium.com/@rebhuinc/database-technical-decisions-6edbfd15e011

Hope you find it useful.
